DROP TABLE IF EXISTS VISITOR;
CREATE TABLE VISITOR
(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME_VISITOR VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    FAMILY_GROUP INT(4) NOT NULL,
    PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS CALENDAR;
CREATE TABLE CALENDAR
(
 ID INT(11) NOT NULL AUTO_INCREMENT,
 DAY_DATE DATE NOT NULL,
 TOTAL_VISITORS INT(4) DEFAULT 0,
 PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS RESERVATION;
CREATE TABLE RESERVATION
(
 ID INT(11) NOT NULL AUTO_INCREMENT,
 VISITOR_ID INT(11) NOT NULL,
 CHECK_IN DATETIME NOT NULL,
 CHECK_OUT DATETIME NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (VISITOR_ID) REFERENCES VISITOR(ID)
);





